config/routes.rb
Babysleep::Application.routes.draw do
  match "home", :to => "static_pages#home", :via => [:get]
  match "about", :to => "static_pages#about", :via => [:get]
  match "help", :to => "static_pages#help", :via => [:get]
  match "error", :to => "static_pages#error", :via => [:get]

  devise_for :users

  root :to => "static_pages#home"

  resources :parents do
    resources :babies
  end 
  resources :babies do
    get 'last_24h_sleeptime', :on => :member
    resources :sleeptimes
  end

end

app/views/nav/_main.html.haml
.navbar.navbar-inverse.navbar-fixed-top
  .navbar-inner
    .container
      %a{:class => "btn btn-navbar", 
        :data => { :toggle => "collapse", :target => ".nav-collapse" }}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

      %a{:class => "brand", :href => url_for(home_path)} Babysleep

      .nav-collapse.collapse
        %ul.nav
          - navigation.each do |link|
            - if (link.include?(:method))
              %li
                = link_to(link[:text], link[:url], :method => link[:method])
            - else
              %li
                = link_to(link[:text], link[:url])

           

app/views/nav/_main_static.html.haml
.navbar.navbar-inverse.navbar-fixed-top
  .navbar-inner
    .container
      %a{:class => "btn btn-navbar", 
        :data => { :toggle => "collapse", :target => ".nav-collapse" }}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

      %a{:class => "brand", :href => url_for(home_path)} Babysleep

      .nav-collapse.collapse
        %ul.nav
          %li
            = link_to(t('navigation.home'), url_for(home_path))
          %li
            = link_to(t('navigation.about'), url_for(about_path))
          %li
            = link_to(t('navigation.help'), url_for(help_path))